[package]
name = "show-scraper"
version = "0.1.0"
authors = ["Alexander Johnson <xander@splunk.com>"]

[dependencies]
reqwest = "0.9.7"
scraper = "0.9.1"
select = "0.4.1"
chrono = "0.4.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"